### PR TITLE
saving and loading models (sklearn API)

### PR DESCRIPTION
**Pull request by gonlairo**
Improve model saving in the sklearn API to ensure future compatibility and safety. Currently, we save the entire object using `torch.save`, which may cause issues with different CEBRA versions. This pull request (PR) tackles this problem by suggesting a solution that involves saving only the model weights and all the arguments used, allowing for complete reconstruction of the CEBRA object at loading time.

Fix https://github.com/AdaptiveMotorControlLab/CEBRA-dev/pull/643

### CODE REVIEW

**Comment by MMathisLab** [comment]
hey @gonlairo could you fix merge conflicts here? thanks!

**Comment by gonlairo** [comment]
> hey @gonlairo could you fix merge conflicts here? thanks!

@MMathisLab we are still developing on dev repo, once its final we'll move it to public and I will fix merge conflifcts.

**Comment by MMathisLab** [comment]
bump @gonlairo :D

**Comment by stes** [comment]
closed in favor of the more recent #69

**Pull request closed without merging**
