### PR TITLE
Fix linting issues

### PR DESCRIPTION
**Pull request by stes**
After merging #167 , this PR fixes all linting issues. This includes:

- whitespace issues and other easy to fix/autofix issues
- long lines (especially in docs!)
- typos in variable names
- duplicate class definitions (a couple in the allen datasets) which can cause unwanted behavior
- some unused imports
- missing variables in some parts of the code not covered by tests yet

### CODE REVIEW

**Comment by stes** [comment]
Seems like my docstring fixes broke some tests. Will fix

**Comment by stes** [comment]
@MMathisLab , this is also finally done! should fix all remaining linting errors in ruff. found some actual errors in the code we missed before before the code in the respective section is not fully covered by tests (should be fixed in a future PR)

**Review by MMathisLab — APPROVED** [review]
Did not locally test, but looking over it looks great, thanks @stes !

**Comment by stes** [comment]
Ok sth broke

Will fix later and then merge

**Pull request merged**
