### PR TITLE
Stop enforcing FloatTensor on TensorDataset

### PR DESCRIPTION
**Pull request by icarosadero**
Changed code to not check for FLoatTensor or LongTensor since tehy are used for compatibility.

### CODE REVIEW

**Comment by stes** [comment]
Hi @icarosadero, thanks for contributing! Could you detail the motivation for this change (e.g. an application case where this enhances functionality)? Any additional context why this change is useful for your application would be great to know before reviewing.

**Comment by icarosadero** [comment]
Hello @stes, let me try to explain with an example. Suppose you have some neural data `X` and `y` loaded in NumPy. You could load it into PyTorch with the `from_numpy`, but this would turn the data into a `torch.Tensor` type, not a `torch.FloatTensor` anymore. So, if you do something like this:

```python
X = np.random.random((100, 100))
y = np.random.random(100)

cebra.data.TensorDataset(
    neural = torch.from_numpy(X),
    discrete = torch.from_numpy(y),
    offset = cebra.data.Offset(1)
)
```

You'll get an error:

```
TypeError: <class 'torch.Tensor'> instead of <class 'torch.FloatTensor'>.
```

Because the old code is checking for an instance of `torch.FloatTensor` on `X`, even though `X` is of float data type:

```
torch.from_numpy(X).dtype == torch.float64 #Returns True
isinstance(torch.from_numpy(X), torch.FloatTensor) #Returns False
```

I came across this error while trying to create a dummy dataset to use the offset feature. I believe the change I made is useful for compatibility.

**Comment by stes** [comment]
Thanks, that makes a lot of sense. Let me check if #166 already fixes this issue, and then get back here!

**Comment by stes** [comment]
Hi @icarosadero , could you check if #166 fixes this issue?

**Comment by icarosadero** [comment]
> Hi @icarosadero , could you check if #166 fixes this issue?

It seems that it does, looks good to me

**Pull request closed without merging**
