### PR TITLE
Release 0.4.0

### PR DESCRIPTION
**Pull request by stes**
Besides bumping the version to 0.4.0, this PR fixes a test in `tests/test_criterions.py` by using a random seed during sampling.

### CODE REVIEW

**Comment by stes** [comment]
Full test suite running

**Comment by stes** [comment]
Forgot to include the datasets into the tests. rerunning right now, will report once they passed, do the test release, then merge into main!

**Comment by stes** [comment]
needs #119 first

**Review by MMathisLab — APPROVED** [review]

**Comment by stes** [comment]
> Forgot to include the datasets into the tests. rerunning right now, will report once they passed, do the test release, then merge into main!

image

all passed

**Pull request merged**
